### ISSUE TITLE
App is crash when purchaseProduct() methode

### ISSUE THREAD

**Issue by lapisanlangit** [Cap-go/native-purchases#46]
Thank you for your plugin, is very easy  to use. I have succeeded get products and show in list price in apps, but when i call purchaseProduct methode, application is crash and automacally out.
   ` try {
    const transaction = await NativePurchases.purchaseProduct({
      productIdentifier: productId,
      productType: PURCHASE_TYPE.INAPP // or PURCHASE_TYPE.SUBS for subscriptions
    });
    console.log('Purchase successful:', transaction);
    // Handle the successful purchase (e.g., unlock content, update UI)
  } catch (error) {
    console.error('Purchase failed:', error);
  }`

no error is shown because apps is out, so I can't give error message. please help me, I am using Angular 18, Ionic 8, Capacitor 6

**Comment by lapisanlangit** [comment]
no info about this?

**Comment by riderx** [comment]
sorry i didn't got email from your first issue.

**Comment by riderx** [comment]
It's ios or android?

**Comment by lapisanlangit** [comment]
Android.. I am using ionic framework

**Comment by lapisanlangit** [comment]
no update?

**Comment by riderx** [comment]
Sorry i didn't saw your answer @WcaleNieWolny can you have a look ?

**Comment by WcaleNieWolny** [comment]
@lapisanlangit Cannot replicate. Please provide more information about the crash

**Comment by lapisanlangit** [comment]
thank you @WcaleNieWolny, there is no error information. I have created new blank ionic app and only create one page for testing. 

home.page.html
`
<ion-header [translucent]="true">
  <ion-toolbar>
    <ion-title> Blank </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content [fullscreen]="true">
  <ion-header collapse="condense">
    <ion-toolbar>
      <ion-title size="large">Blank</ion-title>
    </ion-toolbar>
  </ion-header>

  <div id="container">
    <ion-list>
      <ion-list>
        <ion-item
          button
          *ngFor="let p of listProduct"
          (click)="purchase(p)"
          detail="false"
        >
          <ion-label class="ion-text-wrap">
            {{ p.title }}
            <p>{{ p.description }}</p>
          </ion-label>
          <ion-button slot="end"> {{ p.priceString }} </ion-button>
        </ion-item>
        <ion-item>
          <p class="info">Tap on currency to donation</p>
        </ion-item>
      </ion-list>
    </ion-list>
  </div>
  <ion-button
    color="warning"
    size="default"
    type="button"
    expand="full"
    (click)="refreshData()"
    >Purchase
  </ion-button>
</ion-content>
`
home.page.ts

`

import { Component, OnInit } from '@angular/core';
import { NativePurchases, PURCHASE_TYPE } from '@capgo/native-purchases';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage implements OnInit {
  listProduct: any;

  constructor() {}

  ngOnInit(): void {}
  async getAvailableProducts() {
    try {
      const { products } = await NativePurchases.getProducts({
        productIdentifiers: ['xxxxx'],
        productType: PURCHASE_TYPE.SUBS, // or PURCHASE_TYPE.SUBS for subscriptions
      });
      this.listProduct = products;
    } catch (error) {
      alert(error);
    }
  }

  refreshData() {
    this.getAvailableProducts();
  }
  async purchase(p: any) {
    const transaction = await NativePurchases.purchaseProduct({
      productIdentifier: 'xxxx',
      productType: PURCHASE_TYPE.SUBS, // or PURCHASE_TYPE.SUBS for subscriptions
    });
    // Handle the successful purchase (e.g., unlock content, update UI)
  }
}
`

methode getAvailableProducts() is working properly, products is appear and I clicked one product, but suddenly app is crash and automatic quit. No error information about error. thanks for your help @WcaleNieWolny

**Comment by WcaleNieWolny** [comment]
Please provide the logs from logcat or find the crash log in Google console

![image](https://github.com/user-attachments/assets/8870af32-5a98-4062-a76e-dc96d0700bfa)

**Comment by lapisanlangit** [comment]
thank you  @WcaleNieWolny  in Quality > Android Vitals > Crash and ANRs no information. My apps still only internal testing. I am open log cat in Android Studio and found error log like this.

`
     Serious error executing plugin
                                                                                                    java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native 
   Method)
                                                                                                    	at  
   com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
                                                                                                    	at 
   com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:821)
                                                                                                    	at 
   com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0)
                                                                                                    	at 
   com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)
                                                                                                    	at 
   android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at 
   android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at 
   android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at 
   android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: java.lang.NullPointerException: 
   Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
                                                                                                    	at 
  ee.forgr.nativepurchases.NativePurchasesPlugin.purchaseProduct(NativePurchasesPlugin.java:259)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at 
    com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
                                                                                                    	at 
    com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:821) 
                                                                                                    	at 
   com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0) 
                                                                                                    	at 
   com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8) 
                                                                                                    	at 
   android.os.Handler.handleCallback(Handler.java:942) 
                                                                                                    	at 
   android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at 
   android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at 
  android.os.HandlerThread.run(HandlerThread.java:67) 
2024-11-19 16:38:03.151  6813-7146  AndroidRuntime          com.jumber.app                       E  FATAL EXCEPTION: CapacitorPlugins
                                                                                                    Process: com.jumber.app, PID: 6813
                                                                                                    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                                    	at 
   com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:830)
                                                                                                    	at 
   com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0)
                                                                                                    	at 
   com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)
                                                                                                    	at 
   android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at 
   android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at 
  android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at 
   android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: 
   java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at 
   com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
                                                                                                    	at 
   com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:821)
                                                                                                    	at 
  com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0) 
                                                                                                    	at 
    com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8) 
                                                                                                    	at 
   android.os.Handler.handleCallback(Handler.java:942) 
                                                                                                    	at 
   android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at 
   android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at 
   android.os.HandlerThread.run(HandlerThread.java:67) 
                                                                                                    Caused by: java.lang.NullPointerException: 
   Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
                                                                                                    	at e 
   ee.forgr.nativepurchases.NativePurchasesPlugin.purchaseProduct(NativePurchasesPlugin.java:259)
`

**Comment by WcaleNieWolny** [comment]
Thank you, I will get back with a fix

**Comment by lapisanlangit** [comment]
thank you @WcaleNieWolny
